<?php

$urlhom = "http://fi1.fiorilli.com.br:5663/IssWeb-ejb/IssWebWS/IssWebWS";
$urlprod = "";

$ns = "http://www.abrasf.org.br/nfse.xsd";
$soapns = "http://ws.issweb.fiorilli.com.br/";

$muns = [
    ['ibge' => '1301902', 'mun' => 'Itacoatiara', 'uf' => 'AM', 'url' => ''],
    ['ibge' => '1600303', 'mun' => 'Macapá', 'uf' => 'AP', 'url' => 'http://ws.macapa.ap.gov.br'],
    ['ibge' => '5209705', 'mun' => 'Hidrolândia', 'uf' => 'GO', 'url' => ''],
    ['ibge' => '2101202', 'mun' => 'Bacabal', 'uf' => 'MA', 'url' => ''],
    ['ibge' => '2103307', 'mun' => 'Codó', 'uf' => 'MA', 'url' => ''],
    ['ibge' => '2105401', 'mun' => 'Itapecuru Mirim', 'uf' => 'MA', 'url' => ''],
    ['ibge' => '2108207', 'mun' => 'Pedreiras', 'uf' => 'MA', 'url' => ''],
    ['ibge' => '2109908', 'mun' => 'Santa Inês', 'uf' => 'MA', 'url' => ''],
    ['ibge' => '2112209', 'mun' => 'Timon', 'uf' => 'MA', 'url' => ''],
    ['ibge' => '3124500', 'mun' => 'Estiva', 'uf' => 'MG', 'url' => ''],
    ['ibge' => '3133758', 'mun' => 'Itaú de Minas', 'uf' => 'MG', 'url' => ''],
    ['ibge' => '3134905', 'mun' => 'Jacutinga', 'uf' => 'MG', 'url' => ''],
    ['ibge' => '3146008', 'mun' => 'Ouro Fino', 'uf' => 'MG', 'url' => ''],
    ['ibge' => '3159605', 'mun' => 'Santa Rita do Sapucaí', 'uf' => 'MG', 'url' => ''],
    ['ibge' => '3165404', 'mun' => 'Sapucaí-Mirim', 'uf' => 'MG', 'url' => ''],
    ['ibge' => '3165404', 'mun' => 'Sapucaí-Mirim', 'uf' => 'MG', 'url' => ''],
    ['ibge' => '5000609', 'mun' => 'Amambai', 'uf' => 'MS', 'url' => ''],
    ['ibge' => '5002951', 'mun' => 'Chapadão do Sul', 'uf' => 'MS', 'url' => ''],
    ['ibge' => '5003207', 'mun' => 'Corumbá', 'uf' => 'MS', 'url' => 'http://nfse.corumba.ms.gov.br:8080/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '5003488', 'mun' => 'Dois Irmãos do Buriti', 'uf' => 'MS', 'url' => ''],
    ['ibge' => '5006002', 'mun' => 'Nova Alvorada do Sul', 'uf' => 'MS', 'url' => ''],
    ['ibge' => '5006309', 'mun' => 'Paranaíba', 'uf' => 'MS', 'url' => ''],
    ['ibge' => '5101803', 'mun' => 'Barra do Garças', 'uf' => 'MT', 'url' => ''],
    ['ibge' => '5101902', 'mun' => 'Brasnorte', 'uf' => 'MT', 'url' => ''],
    ['ibge' => '5104807', 'mun' => 'Jaciara', 'uf' => 'MT', 'url' => 'http://intranet.jaciara.mt.gov.br:5661/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '5105234', 'mun' => 'Lambari D Oeste', 'uf' => 'MT', 'url' => ''],
    ['ibge' => '5105622', 'mun' => 'Mirassol D Oeste', 'uf' => 'MT', 'url' => 'http://186.235.81.12:5663/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '1502152', 'mun' => 'Canaã dos Carajás', 'uf' => 'PA', 'url' => ''],
    ['ibge' => '1503606', 'mun' => 'Itaituba', 'uf' => 'PA', 'url' => ''],
    ['ibge' => '1506161', 'mun' => 'Rio Maria', 'uf' => 'PA', 'url' => 'http://177.75.236.132:8080/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '1508407', 'mun' => 'Xinguara', 'uf' => 'PA', 'url' => ''],
    ['ibge' => '2203909', 'mun' => 'Floriano', 'uf' => 'PI', 'url' => ''],
    ['ibge' => '2207702', 'mun' => 'Parnaíba', 'uf' => 'PI', 'url' => ''],
    ['ibge' => '2208007', 'mun' => 'Picos', 'uf' => 'PI', 'url' => ''],
    ['ibge' => '3301157', 'mun' => 'Cardoso Moreira', 'uf' => 'RJ', 'url' => ''],
    ['ibge' => '1100023', 'mun' => 'Ariquemes', 'uf' => 'RO', 'url' => 'http://170.82.43.84:5660/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '1100098', 'mun' => 'Espigão D´Oeste', 'uf' => 'RO', 'url' => ''],
    ['ibge' => '1100114', 'mun' => 'Jaru', 'uf' => 'RO', 'url' => ''],
    ['ibge' => '1100122', 'mun' => 'Ji-Paraná', 'uf' => 'RO', 'url' => 'http://177.124.184.59:5660/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '1100130', 'mun' => 'Machadinho D´Oeste', 'uf' => 'RO', 'url' => ''],
    ['ibge' => '1100155', 'mun' => 'Ouro Preto do Oeste', 'uf' => 'RO', 'url' => ''],
    ['ibge' => '4315313', 'mun' => 'Quatro Irmãos', 'uf' => 'RS', 'url' => ''],
    ['ibge' => '4311809', 'mun' => 'Marau', 'uf' => 'RS', 'url' => 'http://nfse.pmmarau.com.br:8080/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '4320404', 'mun' => 'Serafina Corrêa', 'uf' => 'RS', 'url' => ''],
    ['ibge' => '4321634', 'mun' => 'Tres Arroios', 'uf' => 'RS', 'url' => 'http://portal.pmtresarroios.com.br:8888/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3501004', 'mun' => 'Altinópolis', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3501509', 'mun' => 'Alvinlândia', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3501806', 'mun' => 'Américo de Campos', 'uf' => 'SP', 'url' => 'http://189.108.31.114:8080/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3502903', 'mun' => 'Araçoiaba da Serra', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3504008', 'mun' => 'Assis', 'uf' => 'SP', 'url' => 'https://nfsews.assis.sp.gov.br/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3504602', 'mun' => 'Bady Bassitt', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3504800', 'mun' => 'Bálsamo', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3505203', 'mun' => 'Bariri', 'uf' => 'SP', 'url' => 'http://sipweb.bariri.sp.gov.br:5661/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3507803', 'mun' => 'Brodowski', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3508306', 'mun' => 'Cabrália Paulista', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3509304', 'mun' => 'Cajobi', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3510104', 'mun' => 'Cândido Rodrigues', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3510302', 'mun' => 'Capela do Alto', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3511300', 'mun' => 'Cedral', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3512100', 'mun' => 'Colômbia', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3512902', 'mun' => 'Cosmorama', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3514403', 'mun' => 'Dracena', 'uf' => 'SP', 'url' => 'http://187.17.201.221:8080/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3514502', 'mun' => 'Duartina', 'uf' => 'SP', 'url' => 'http://186.224.0.62:5661/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3515608', 'mun' => 'Fernando Prestes', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3515509', 'mun' => 'Fernandópolis', 'uf' => 'SP', 'url' => 'http://servicos.fernandopolis.sp.gov.br:8080/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3516705', 'mun' => 'Garça', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3517208', 'mun' => 'Guaiçara', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3517307', 'mun' => 'Guaimbê', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3517406', 'mun' => 'Guaíra', 'uf' => 'SP', 'url' => 'http://186.211.16.210:5661/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3517703', 'mun' => 'Guará', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3518206', 'mun' => 'Guararapes', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3519055', 'mun' => 'Holambra', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3519303', 'mun' => 'Ibaté', 'uf' => 'SP', 'url' => 'http://200.205.131.110:5661/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3519600', 'mun' => 'Ibitinga', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3520103', 'mun' => 'Igarapava', 'uf' => 'SP', 'url' => 'http://138.117.189.204:8080/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3520707', 'mun' => 'Indiaporã', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3520806', 'mun' => 'Inúbia Paulista', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3521903', 'mun' => 'Itajobi', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3525706', 'mun' => 'José Bonifácio', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3526001', 'mun' => 'Junqueirópolis', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3526407', 'mun' => 'Laranjal Paulista', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3529203', 'mun' => 'Martinópolis', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3529708', 'mun' => 'Miguelópolis', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3530102', 'mun' => 'Mirandópolis', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3530409', 'mun' => 'Mirassolândia', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3531100', 'mun' => 'Mongaguá', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3531407', 'mun' => 'Monte Aprazível', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3532009', 'mun' => 'Morungaba', 'uf' => 'SP', 'url' => 'http://servicos.morungaba.sp.gov.br:5600/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3532801', 'mun' => 'Nova Aliança', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3533007', 'mun' => 'Nova Granada', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3533502', 'mun' => 'Novo Horizonte', 'uf' => 'SP', 'url' => 'http://nfews.novohorizonte.sp.gov.br/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3535101', 'mun' => 'Palmares Paulista', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3535408', 'mun' => 'Panorama', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3536307', 'mun' => 'Patrocínio Paulista', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3536604', 'mun' => 'Paulo de Faria', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3537107', 'mun' => 'Pedreira', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3538907', 'mun' => 'Pirajuí', 'uf' => 'SP', 'url' => 'http://189.57.88.130:3392/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3539004', 'mun' => 'Pirangi', 'uf' => 'SP', 'url' => 'http://portal.pmpirangi.com.br:5661/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3539202', 'mun' => 'Pirapozinho', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3540200', 'mun' => 'Pontal', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3540804', 'mun' => 'Potirendaba', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3541604', 'mun' => 'Promissão', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3541703', 'mun' => 'Quatá', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3541802', 'mun' => 'Queiroz', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3542909', 'mun' => 'Ribeirão Bonito', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3543105', 'mun' => 'Ribeirão Corrente', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3544004', 'mun' => 'Rio das Pedras', 'uf' => 'SP', 'url' => 'http://riodaspedras.brgov.com.br:5661/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3544202', 'mun' => 'Riolândia', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3544608', 'mun' => 'Sabino', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3544806', 'mun' => 'Sales', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3544905', 'mun' => 'Sales Oliveira', 'uf' => 'SP', 'url' => 'http://issweb.salesoliveira.sp.gov.br:9090/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3545308', 'mun' => 'Salto de Pirapora', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3547700', 'mun' => 'Santo Anastácio', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3548005', 'mun' => 'Santo Antônio de Posse', 'uf' => 'SP', 'url' => 'http://177.36.128.42:8080/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3549409', 'mun' => 'São Joaquim da Barra', 'uf' => 'SP', 'url' => 'http://187.72.128.113:5661/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3551405', 'mun' => 'Serra Azul', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3551603', 'mun' => 'Serra Negra', 'uf' => 'SP', 'url' => 'http://intra.serranegra.sp.gov.br/IssWeb-ejb/IssWebWS/IssWebWS'],
    ['ibge' => '3552304', 'mun' => 'Sud Mennucci', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3555356', 'mun' => 'Ubarana', 'uf' => 'SP', 'url' => ''],
    ['ibge' => '3555802', 'mun' => 'Urânia', 'uf' => 'SP', 'url' => ''],
];

$am = [];
foreach ($muns as $m) {
    $am["{$m['ibge']}"] = [
        "municipio"   => $m['mun'],
        "uf"          => $m['uf'],
        "homologacao" => $urlhom,
        "producao"    => $m['url'],
        "version"     => "2.01",
        "msgns"       => $ns,
        "soapns"      => $soapns
    ];
}

file_put_contents('../storage/urls_webservices.json', json_encode($am, JSON_PRETTY_PRINT));
